### ISSUE TITLE
A question about solvePnP

### ISSUE THREAD

**Issue by andrealu2012** [shimat/opencvsharp#1016]
**Because i need to use existing extrinsic parameter,so add a "true"in SolvePnP:(if without "true",no exception.)**

                Cv2.SolvePnP(WorldPts, ImgPts, M, Dist, Rvec, Tvec,**true**);//if i add "true" in solvePnP,when runs it will show exception:
//==== exception:==========
OpenCvSharp.OpenCVException
  HResult=0x80131500
  Message=(rtype == CV_32F || rtype == CV_64F) && (ttype == CV_32F || ttype == CV_64F)
  Source=OpenCvSharp
  StackTrace:
   at OpenCvSharp.NativeMethods.<>c.<.cctor>b__1805_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userdata)
   at OpenCvSharp.NativeMethods.calib3d_solvePnP_InputArray(IntPtr selfectPoints, IntPtr imagePoints, IntPtr cameraMatrix, IntPtr distCoeffs, IntPtr rvec, IntPtr tvec, Int32 useExtrinsicGuess, Int32 flags)
   at OpenCvSharp.Cv2.SolvePnP(InputArray objectPoints, InputArray imagePoints, InputArray cameraMatrix, InputArray distCoeffs, OutputArray rvec, OutputArray tvec, Boolean useExtrinsicGuess, SolvePnPFlags flags)
   at GHCmpTest.SolvePnP.SolveInstance(IGH_DataAccess DA) in D:\temp\GHCmpTest\GHCmpTest\SolvePnP.cs:line 157
   at Grasshopper.Kernel.GH_Component.Solution_Compute_MixedAccess(GH_StructureIterator it)

//==================

**This is my code:**    

            if (rvec==null)//rvec is a List<double>
                {
                    rvec = new List<double> { 1.1, 1.08, -1.45 };
                }
                OutputArray Rvec = OutputArray.Create<double>(rvec);

                if(tvec==null)//tvec is a List<double>
                {
                    tvec = new List<double> { 10, -10, 100 };
                }
                OutputArray Tvec = OutputArray.Create<double>(tvec);

                Cv2.SolvePnP(WorldPts, ImgPts, M, Dist, Rvec, Tvec,**true**);//if i add "true" in solvePnP,when runs it will show exception:

//=====================================
Thank you!

**Comment by ravazquez** [comment]
Just a guess: rtype == CV_32F || rtype == CV_64F) && (ttype == CV_32F || ttype == CV_64F probably means your rvec and tvec Mats need to be of a 32 or 64 Float MatType
