### ISSUE TITLE
OpenCVException: npoints >= 0 && (depth == CV_32F || depth == CV_32S)

### ISSUE THREAD

**Issue by soundmartell** [shimat/opencvsharp#1064]
# Summary of your issue
Cv2.ContourArea give me an Exception.
If I remove  area = Cv2.ContourArea(closing); the code run without errors.
I can see my code look like this in this issue [#829 ](https://github.com/shimat/opencvsharp/issues/829)
But the issue was not about and Exception so I assume It was working. Was it?
I check the "closing" Mat and it is a CV_8UC1.
What am I doing wrong?

# Environment

Visual Studio 2019
OpenCvSharp 4.4.0.20200915 

# What did you do when you faced the problem?

Write here

## Example code:

```
                  
                    kernel = Mat.Ones(rows: 9, 9, MatType.CV_8U);
                    

                    //Aplicamos Morphology 
                    Cv2.MorphologyEx(
                        frame2,
                        opening_ori,
                        MorphTypes.Open,
                        kernel
                        );
                    Cv2.MorphologyEx(
                        opening_ori,
                        closing_ori,
                        MorphTypes.Close,
                        kernel

                        );
                    Cv2.MorphologyEx(
                        thresh1,
                        opening,

                        MorphTypes.Open,
                        kernel

                        );
                    Cv2.MorphologyEx(
                        opening,
                        closing,

                        MorphTypes.Close,
                        kernel

                        );


                    // Encontrar contornos...
                    Cv2.FindContours(
                        closing,
                        out contours,
                        out hierarchy,
                        RetrievalModes.External,
                        ContourApproximationModes.ApproxSimple
                        );

             
                    foreach (OpenCvSharp.Point[] contour in contours)
                    {
                        num_cnt += 1;

                              //Exception here!!!!
                            area = Cv2.ContourArea(closing);
                     
                         

                    }

```

## Output:

```
Exception thrown: 'OpenCvSharp.OpenCVException' in OpenCvSharp.dll
OpenCvSharp.OpenCVException: npoints >= 0 && (depth == CV_32F || depth == CV_32S)
   at OpenCvSharp.NativeMethods.<>c.<.cctor>b__1600_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.NativeMethods.imgproc_contourArea_InputArray(IntPtr contour, Int32 oriented, Double& returnValue)
   at OpenCvSharp.Cv2.ContourArea(InputArray contour, Boolean oriented)
```

## What did you intend to be?
Calculate Contours Areas.

**Comment by shimat** [comment]
Please try the following

```
area = Cv2.ContourArea(closing);
```
⬇️ 
```
area = Cv2.ContourArea(contour);
```

**Comment by soundmartell** [comment]
> Please try the following
> 
> ```
> area = Cv2.ContourArea(closing);
> ```
> 
> ⬇️
> 
> ```
> area = Cv2.ContourArea(contour);
> ```

Thanks
