### ISSUE TITLE
【SOLVED】Cv2.CalibrateCamera, error: fabs(sc) > DBL_EPSILON, OpencvSharp 4.4.5

### ISSUE THREAD

**Issue by 12343954** [shimat/opencvsharp#1093]
# Can anybody give the correct camera calibration demo?

# Environment
OpencvSharp 4.4.5

# `Cv2.CalibrateCamera(obj_points, img_points, ImgSize, cameraMatrix, distCoeffs, out rvecs, out tvecs, CalibrationFlags.None, null);` 
Exception with `fabs(sc) > DBL_EPSILON`

## Example code:

```
public int Calibrate_Images()
{
    int result = 0;

    List<List<Point3f>> obj_points = new List<List<Point3f>>();
    List<List<Point2f>> img_points = new List<List<Point2f>>();
    List<Point3f> one_img_points = new List<Point3f>();

    Size ImgSize;
    Int Image_Width, Image_Height;

    try
    {
        foreach (var imgfile in IMGs)
        {

            Mat img = Cv2.ImRead(imgfile.FileName, ImreadModes.Color);
            Mat gray = img.CvtColor(ColorConversionCodes.BGR2GRAY);
            Point2f[] corners = null;
            Point2f[] corners_subpix = null;

            if (ImgSize.Width == 0 || ImgSize.Height == 0)
            {
                ImgSize = img.Size();
                Image_Width = ImgSize.Width;
                Image_Height = ImgSize.Height;
            }


            bool found = Cv2.FindChessboardCorners(img, new Size(PAT_ROW, PAT_COL), out corners, ChessboardFlags.None);
            if (found)
            {
                //keep finding sub pix
                corners_subpix = Cv2.CornerSubPix(gray, corners, new Size(6, 6), new Size(-1, -1), new TermCriteria(CriteriaType.Eps | CriteriaType.MaxIter, 30, 0.03));
                if (corners_subpix != null)
                {
                    obj_points.Add(one_img_points);
                    img_points.Add(corners_subpix.ToList());

                    //objectPoints.Add(one_img_points);

                    Cv2.DrawChessboardCorners(img, new Size(PAT_ROW, PAT_COL), corners_subpix, true);

                    img.SaveImage($"{CornerFolder}_{DateTime.Now.ToString("ffff")}.jpg");
                }
            }
            img.Dispose();
            gray.Dispose();
        }

        Vec3d[] rvecs;
        Vec3d[] tvecs;

        double[,] cameraMatrix = new double[3, 3];
        double[] distCoeffs = new double[5];

        //------------------------- above code is ok ------------------
        // an error occurred here, throw an exception.
        var err = Cv2.CalibrateCamera(obj_points, img_points, ImgSize, cameraMatrix, distCoeffs, out rvecs, out tvecs, CalibrationFlags.None, null);

        FileStorage fs = new FileStorage(InnerParamsFolder + "Intrinsics.xml", FileStorage.Mode.FormatYaml | FileStorage.Mode.Write);

        fs.Write("Intrinsics", Data2Intrinsics(camera_matrix));
        fs.Dispose();

        fs = new FileStorage(InnerParamsFolder + "Distortion.xml", FileStorage.Mode.FormatYaml | FileStorage.Mode.Write);
        fs.Write("Distortion", Data2Distort(dist_coeffs));
        fs.Dispose();

    }
    catch (Exception ex)
    {
        result = -1;
    }
    return result;
}
```

## Output:
```
Exception: fabs(sc) > DBL_EPSILON
```

```
   at OpenCvSharp.NativeMethods.<>c.<.cctor>b__1600_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.NativeMethods.calib3d_calibrateCamera_vector(IntPtr[] objectPoints, Int32 opSize1, Int32[] opSize2, IntPtr[] imagePoints, Int32 ipSize1, Int32[] ipSize2, Size imageSize, Double* cameraMatrix, Double[] distCoeffs, Int32 distCoeffsSize, IntPtr rvecs, IntPtr tvecs, Int32 flags, TermCriteria criteria, Double& returnValue)
   at OpenCvSharp.Cv2.CalibrateCamera(IEnumerable`1 objectPoints, IEnumerable`1 imagePoints, Size imageSize, Double[,] cameraMatrix, Double[] distCoeffs, Vec3d[]& rvecs, Vec3d[]& tvecs, CalibrationFlags flags, Nullable`1 criteria)
   at Darknet.YoloV3.Business.MyCameraCalibration.Calibrate_Chess_Images_Array() in D:\Tensorflow2\C#_YOLOv3\Darknet.YoloV3\Darknet.YoloV3\Business\MyCameraCalibration.cs:line 173
```

## What did you intend to be?
anyone who can fix it? thank you !

**Comment by 12343954** [comment]
Soloved it, see https://youtu.be/ZZ5M7Q5ZWX4
