### ISSUE TITLE
How to run this library in a Windows docker container?

### ISSUE THREAD

**Issue by PolarGoose** [shimat/opencvsharp#1262]
I'm developing a C# .Net 4.8 Windows application which uses `OpenCvSharp4.Windows 4.5.2.20210404` Nuget package.
Everything works well out of the box.
However, when I try to run my application in a Windows docker container based on `mcr.microsoft.com/dotnet/framework/sdk:4.8` the application fails to run with the exception:
```
System.TypeInitializationException : The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
  ----> System.DllNotFoundException : Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OpenCvSharp.Internal.NativeMethods.core_Mat_new2(Int32 rows, Int32 cols, Int32 type, IntPtr& returnValue)
   at OpenCvSharp.Mat..ctor(Int32 rows, Int32 cols, MatType type)
   at MyProject.Imaging.Algorithms.BlurLevelCalculator..ctor(Int32 imageWidth, Int32 imageHeight) in C:\l\MyProject\Imaging\Algorithms\BlurLevelCalculator.cs:line 17
   at MyProject.Imaging.Test.TestBlurLevelCalculator.Sharpness_is_calculated_correctly() in C:\l\MyProject\Imaging.Test\AlgorithmsTest\BlurLevelCalculator\TestBlurLevelCalculator.cs:line 33
--DllNotFoundException
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()
```
Even thought I just mount whole Release folder inside a docker container and try to run the application in the same way I do on my host machine.

I assume that the problem is that Windows docker containers are lacking some features/dlls which are required by this library.
Does anybody know if it is possible to make this library work inside a Windows docker container?

**Comment by AvenSun** [comment]
of course It does work well inside a container.
you can check the missing library of OpenCvSharpExtern.dll via [dependency walker](https://www.dependencywalker.com/) inside the container.
then just copy these libraries from your dev PC  into the container.
It should work successfully.

**Comment by PolarGoose** [comment]
@AvenSun,

Thank you for the reply. Have you managed to make it work? Could you please share what dlls are needed to be copied? I have tried to use [Dependencies ](https://github.com/lucasg/Dependencies) and it showed that I had missing dll's even on my host machine on which OpenCvSharp ran properly. I tried to compare the output of this tool from a Docker container and a host machine but I couldn't make sense out of it, they both had a lot of dlls missing.

**Comment by AvenSun** [comment]
yes, I've made it work on Windows/Linux/Linux arm64.
generally you can just copy the missing libraries within the first level of node
somthing looks like the attached image below (marked with yellow)
![missing](https://user-images.githubusercontent.com/5615543/118166715-66380080-b458-11eb-8133-85704bedd8f0.jpg)
