### ISSUE TITLE
WpfExtensions.BitmapSourceConverter.ToMat(BitmapSource src) cause AccessViolationException

### ISSUE THREAD

**Issue by Cechiino** [shimat/opencvsharp#1416]
# Summary of your issue

Converting of BitmapSource to Mat cause AccessViolationException
Same conversion code was Ok with OpenCvSharp3-AnyCPU.3.4.1.20180830

# Environment

Visual Studio 2019 v 16.4.6, WPF application running .NET Framework 4.7.1
OpenCvSharp4              version 4.4.0.20200725
OpenCvSharp4.WpfExtensions  4.4.0.20200725
same issue in 4.5.3.20211228

# What did you do when you faced the problem?

I tried to load png image file that is included in solution with Build Action: Resource

## Example code:

```
image = new BitmapImage(
                new Uri(
                    "pack://application:,,,/---;Component/TestImages/image.png",
                    UriKind.RelativeOrAbsolute)).ToMat();
```
--- hides mine app structure

## Output:

```
Exception is: AccessViolationException - Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
-----------------------------------------------
At the time of the exception, the container was:
....
   ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenCvSharp.NativeMethods.core_Mat_cols(IntPtr self, Int32& returnValue)
   at OpenCvSharp.Mat.get_Cols()
   at OpenCvSharp.WpfExtensions.BitmapSourceConverter.ToMat(BitmapSource src, Mat dst)
   at OpenCvSharp.WpfExtensions.BitmapSourceConverter.ToMat(BitmapSource src)
```

## What did you intend to be?

Image should load and get cornverted to Mat. Then used in WPF view layer

**Comment by Cechiino** [comment]
This was caused by mess in binaries. Once everything was cleaned, This conversion works properly.
