### ISSUE TITLE
Fisheye op size exception

### ISSUE THREAD

**Issue by darahan** [shimat/opencvsharp#1442]
# Fisheye op size exception

# Environment

Windows 11 ,NET Standard 2.0.

# What did you do when you faced the problem?

I tried to convert my camera calibration to fisheye camera calibration, as shown in the code below. It gave me op size exception shown below. As far as I can see the sizes of the arrays were correct. 

## Example code:

```
                    var objectPoints = Create3DChessboardCorners(chessboardSize, 1.0f); //IEnumerable<Point3f>
                    var imagePoints = corners.ToArray(); // Point2f[]
                    var cameraMatrix = new double[,] { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } };



                    var distCoeffs = new double[5];
                    var rms = Cv2.CalibrateCamera(new[] { objectPoints }, new[] { imagePoints }, FilteredImage.Size(), cameraMatrix,
                        distCoeffs, out var rotationVectors, out var translationVectors,
                        CalibrationFlags.UseIntrinsicGuess | CalibrationFlags.FixK5);
                    var objectMat = new List<Mat>();
                    foreach( var objectPoint in objectPoints)
                    {
                        double[] vec = { objectPoint.X, objectPoint.Y, objectPoint.Z };
                        var mat = new Mat(3, 1, MatType.CV_32FC3, vec);
                        
                        objectMat.Add(mat);
                    }
                    var imageMat = new List<Mat>();
                    foreach (var imagePoint in imagePoints)
                    {
                        double[] vec = { imagePoint.X, imagePoint.Y};
                        var mat = new Mat(2, 1, MatType.CV_32FC2, vec);

                        imageMat.Add(mat);
                    }
                    var kMatrix = new Mat(3, 3, MatType.CV_32FC1);
                    var dVector = new Mat(4, 1, MatType.CV_32FC1);

                    var rms2 = Cv2.FishEye.Calibrate(objectMat, imageMat, FilteredImage.Size(), kMatrix,
                        dVector, out var rvecs, out var tvecs);
                    CalibrationData.CameraMatrix = ExtensionMethods.ToJaggedArray(cameraMatrix);
                    CalibrationData.DistortionMatrix = distCoeffs;

```

## Output:

```
The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' OpenCvSharp.OpenCVException: The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array'
   at OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b__1675_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.Internal.NativeMethods.calib3d_fisheye_calibrate(IntPtr objectPoints, IntPtr imagePoints, Size imageSize, IntPtr K, IntPtr D, IntPtr rvecs, IntPtr tvecs, Int32 flags, TermCriteria criteria, Double& returnValue)
   at OpenCvSharp.Cv2.FishEye.Calibrate(IEnumerable`1 objectPoints, IEnumerable`1 imagePoints, Size imageSize, InputOutputArray k, InputOutputArray d, IEnumerable`1& rvecs, IEnumerable`1& tvecs, FishEyeCalibrationFlags flags, Nullable`1 criteria)
```

## What did you intend to be?
No exception

**Comment by darahan** [comment]
Found it! The image point matrix needs to be a 3D vector instead of a 2D vector.
`                  foreach (var imagePoint in imagePoints)
                    {
                        double[] vec = { imagePoint.X, imagePoint.Y, 0 };
                        var mat = new Mat(3, 1, MatType.CV_32FC2, vec);

                        imageMat.Add(mat);
                    }`
