### ISSUE TITLE
OpenCVSharp for MAUI on Android and IOS

### ISSUE THREAD

**Issue by pierre01** [shimat/opencvsharp#1509]
# Summary of your issue

Make OpenCVSharp work with MAUI on Android and IOS

# Environment

.NET 7.0  MAUI  - Android, IOS

# What did you do when you faced the problem?

I tried to make it work but it throws exceptions.

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

## What did you intend to be?

Work on MAUI Android as well as it does on windows.

**Comment by DamianSuess** [comment]
yes please <3

**Comment by samirgcofficial** [comment]
Any updates ?

**Comment by Hrishikesh46779** [comment]
will it work on maui android and ios ?

**Comment by sdcb** [comment]
Hey all, please try my self-compiled OpenCvSharp4 runtime, it's a mini runtime, only provided core, imgcodec, imgproc modules, I tested in my MAUI & Avalonia ARM64 android phone:

| Id                                     | Version | Size      | OS      | Arch |
| -------------------------------------- | ----- | -------- | ------------ | ----- |
| Sdcb.OpenCvSharp4.mini.runtime.centos.7-arm64      | [![NuGet](https://img.shields.io/nuget/v/Sdcb.OpenCvSharp4.mini.runtime.centos.7-arm64.svg)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.centos.7-arm64) | 3.23MB  | CentOS 7     | ARM64 |
| Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64       | [![NuGet](https://img.shields.io/nuget/v/Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64.svg)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64) | 16.75MB | CentOS 7     | x64   |
| Sdcb.OpenCvSharp4.mini.runtime.debian.11-arm64    | [![NuGet](https://img.shields.io/nuget/v/Sdcb.OpenCvSharp4.mini.runtime.debian.11-arm64.svg)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.11-arm64) | 4.05MB  | Debian 11    | ARM64 |
| Sdcb.OpenCvSharp4.mini.runtime.debian.11-x64      | [![NuGet](https://img.shields.io/nuget/v/Sdcb.OpenCvSharp4.mini.runtime.debian.11-x64.svg)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.11-x64) | 18.13MB | Debian 11    | x64   |
| Sdcb.OpenCvSharp4.mini.runtime.debian.12-arm64    | [![NuGet](https://img.shields.io/nuget/v/Sdcb.OpenCvSharp4.mini.runtime.debian.12-arm64.svg)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.12-arm64) | 4.18MB  | Debian 12    | ARM64 |
| Sdcb.OpenCvSharp4.mini.runtime.debian.12-x64      | [![NuGet](https://img.shields.io/nuget/v/Sdcb.OpenCvSharp4.mini.runtime.debian.12-x64.svg)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.12-x64) | 17.47MB | Debian 12    | x64   |
| Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64 | [![NuGet](https://img.shields.io/nuget/v/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64.svg)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64) | 4.18MB  | Ubuntu 22.04 | ARM64 |
| Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64   | [![NuGet](https://img.shields.io/nuget/v/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64.svg)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64) | 17.47MB | Ubuntu 22.04 | x64   |
| Sdcb.OpenCvSharp4.mini.runtime.android-arm64      | [![NuGet](https://img.shields.io/nuget/v/Sdcb.OpenCvSharp4.mini.runtime.android-arm64.svg)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.android-arm64) | 4.04MB  | **Android**      | ARM64 |

**Comment by vraziel** [comment]
> Hey all, please try my self-compiled OpenCvSharp4 runtime, it's a mini runtime, only provided core, imgcodec, imgproc modules, I tested in my MAUI & Avalonia ARM64 android phone:
> 
> Id	Version	Size	OS	Arch
> Sdcb.OpenCvSharp4.mini.runtime.centos.7-arm64	[![NuGet](https://camo.githubusercontent.com/03a0d521ff702e9db765186f732e14ecc6c69b0244b413af94350b1c9ad73032/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e63656e746f732e372d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.centos.7-arm64)	3.23MB	CentOS 7	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64	[![NuGet](https://camo.githubusercontent.com/67adea573e02c2ce5a0b412a1e031b380b14823df42723dcafd637d7c2353b10/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e63656e746f732e372d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64)	16.75MB	CentOS 7	x64
> Sdcb.OpenCvSharp4.mini.runtime.debian.11-arm64	[![NuGet](https://camo.githubusercontent.com/55e403faceb65cb1a10ef0b38f1a5892da67d255c214fe86041b3e529f2c4c18/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31312d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.11-arm64)	4.05MB	Debian 11	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.debian.11-x64	[![NuGet](https://camo.githubusercontent.com/8908a41339fa665db21794271d2ddbc1ebb0d863aab699914b4530b7cb17a78f/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31312d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.11-x64)	18.13MB	Debian 11	x64
> Sdcb.OpenCvSharp4.mini.runtime.debian.12-arm64	[![NuGet](https://camo.githubusercontent.com/3b8cd5dd102154270d4f987fe7b4dfdbf84d55abbc0656a86872239628aa7c82/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31322d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.12-arm64)	4.18MB	Debian 12	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.debian.12-x64	[![NuGet](https://camo.githubusercontent.com/7579f4ae19bed0410bf17e37ffcb74e9e93239252e9c28ce7bb5b5c9738b4817/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31322d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.12-x64)	17.47MB	Debian 12	x64
> Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64	[![NuGet](https://camo.githubusercontent.com/ff1898a83b801011fce0e1ad2a2ba343b6e9c906d443c57902ef47f1a2540709/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e7562756e74752e32322e30342d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64)	4.18MB	Ubuntu 22.04	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64	[![NuGet](https://camo.githubusercontent.com/479189050fb605d961092e4c9d8f7caeb757e409bdc87e8359e644f8107df98f/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e7562756e74752e32322e30342d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64)	17.47MB	Ubuntu 22.04	x64
> Sdcb.OpenCvSharp4.mini.runtime.android-arm64	[![NuGet](https://camo.githubusercontent.com/0f2051d11852599019aaa721d404e03749ece9d64acd200a7dfa60d8265ea000/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e616e64726f69642d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.android-arm64)	4.04MB	**Android**	ARM64

I've tried your packages (Sdcb.OpenCvSharp4.mini.runtime.android-arm64 ), but I always face with the same error on android emulator:

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
[mono-rt]  ---> System.DllNotFoundException: OpenCvSharpExtern
[mono-rt]    at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
[mono-rt]    at OpenCvSharp.Internal.NativeMethods..cctor()
[mono-rt]    --- End of inner exception stack trace ---
[mono-rt]    at OpenCvSharp.Cv2.ImRead(String fileName, ImreadModes flags)


How to make it work?

**Comment by sdcb** [comment]
Can you try test in MAUI or Avalonia?, Xamarin.Android seems not working.

**Comment by cemalgulbeyaz** [comment]
> Hey all, please try my self-compiled OpenCvSharp4 runtime, it's a mini runtime, only provided core, imgcodec, imgproc modules, I tested in my MAUI & Avalonia ARM64 android phone:
> 
> Id	Version	Size	OS	Arch
> Sdcb.OpenCvSharp4.mini.runtime.centos.7-arm64	[![NuGet](https://camo.githubusercontent.com/03a0d521ff702e9db765186f732e14ecc6c69b0244b413af94350b1c9ad73032/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e63656e746f732e372d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.centos.7-arm64)	3.23MB	CentOS 7	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64	[![NuGet](https://camo.githubusercontent.com/67adea573e02c2ce5a0b412a1e031b380b14823df42723dcafd637d7c2353b10/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e63656e746f732e372d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64)	16.75MB	CentOS 7	x64
> Sdcb.OpenCvSharp4.mini.runtime.debian.11-arm64	[![NuGet](https://camo.githubusercontent.com/55e403faceb65cb1a10ef0b38f1a5892da67d255c214fe86041b3e529f2c4c18/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31312d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.11-arm64)	4.05MB	Debian 11	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.debian.11-x64	[![NuGet](https://camo.githubusercontent.com/8908a41339fa665db21794271d2ddbc1ebb0d863aab699914b4530b7cb17a78f/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31312d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.11-x64)	18.13MB	Debian 11	x64
> Sdcb.OpenCvSharp4.mini.runtime.debian.12-arm64	[![NuGet](https://camo.githubusercontent.com/3b8cd5dd102154270d4f987fe7b4dfdbf84d55abbc0656a86872239628aa7c82/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31322d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.12-arm64)	4.18MB	Debian 12	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.debian.12-x64	[![NuGet](https://camo.githubusercontent.com/7579f4ae19bed0410bf17e37ffcb74e9e93239252e9c28ce7bb5b5c9738b4817/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31322d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.12-x64)	17.47MB	Debian 12	x64
> Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64	[![NuGet](https://camo.githubusercontent.com/ff1898a83b801011fce0e1ad2a2ba343b6e9c906d443c57902ef47f1a2540709/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e7562756e74752e32322e30342d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64)	4.18MB	Ubuntu 22.04	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64	[![NuGet](https://camo.githubusercontent.com/479189050fb605d961092e4c9d8f7caeb757e409bdc87e8359e644f8107df98f/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e7562756e74752e32322e30342d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64)	17.47MB	Ubuntu 22.04	x64
> Sdcb.OpenCvSharp4.mini.runtime.android-arm64	[![NuGet](https://camo.githubusercontent.com/0f2051d11852599019aaa721d404e03749ece9d64acd200a7dfa60d8265ea000/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e616e64726f69642d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.android-arm64)	4.04MB	**Android**	ARM64

Your android runtime package is contains only arm64, People try to use it with Emulator on Windos (or Linux, MacOS) platform by X86_x64 architectured CPU. If you figure out that problem with a runtime package which contains other CPU architectures it may work. More information android CPU architectures : [https://developer.android.com/ndk/guides/abis](https://developer.android.com/ndk/guides/abis)

**Comment by sdcb** [comment]
Understand, but I currently only interested to run it in real Android ARM64 phone instead of emulator, in future I might publish new nuget package that supports android-x64.

**Comment by cemalgulbeyaz** [comment]
> Hi @CrushDSS , good news, I published opencvsharp4's mini android-x64 runtime here: https://github.com/sdcb/opencvsharp-mini-runtime
> 
> # Packages
> Id	Version	Size	OS	Arch
> Sdcb.OpenCvSharp4.mini.runtime.centos.7-arm64	[![NuGet](https://camo.githubusercontent.com/03a0d521ff702e9db765186f732e14ecc6c69b0244b413af94350b1c9ad73032/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e63656e746f732e372d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.centos.7-arm64)	3.23MB	CentOS 7	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64	[![NuGet](https://camo.githubusercontent.com/67adea573e02c2ce5a0b412a1e031b380b14823df42723dcafd637d7c2353b10/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e63656e746f732e372d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64)	16.75MB	CentOS 7	x64
> Sdcb.OpenCvSharp4.mini.runtime.debian.11-arm64	[![NuGet](https://camo.githubusercontent.com/55e403faceb65cb1a10ef0b38f1a5892da67d255c214fe86041b3e529f2c4c18/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31312d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.11-arm64)	4.05MB	Debian 11	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.debian.11-x64	[![NuGet](https://camo.githubusercontent.com/8908a41339fa665db21794271d2ddbc1ebb0d863aab699914b4530b7cb17a78f/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31312d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.11-x64)	18.13MB	Debian 11	x64
> Sdcb.OpenCvSharp4.mini.runtime.debian.12-arm64	[![NuGet](https://camo.githubusercontent.com/3b8cd5dd102154270d4f987fe7b4dfdbf84d55abbc0656a86872239628aa7c82/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31322d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.12-arm64)	4.18MB	Debian 12	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.debian.12-x64	[![NuGet](https://camo.githubusercontent.com/7579f4ae19bed0410bf17e37ffcb74e9e93239252e9c28ce7bb5b5c9738b4817/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e64656269616e2e31322d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.debian.12-x64)	17.47MB	Debian 12	x64
> Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64	[![NuGet](https://camo.githubusercontent.com/ff1898a83b801011fce0e1ad2a2ba343b6e9c906d443c57902ef47f1a2540709/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e7562756e74752e32322e30342d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-arm64)	4.18MB	Ubuntu 22.04	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64	[![NuGet](https://camo.githubusercontent.com/479189050fb605d961092e4c9d8f7caeb757e409bdc87e8359e644f8107df98f/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e7562756e74752e32322e30342d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.ubuntu.22.04-x64)	17.47MB	Ubuntu 22.04	x64
> Sdcb.OpenCvSharp4.mini.runtime.android-arm64	[![NuGet](https://camo.githubusercontent.com/0f2051d11852599019aaa721d404e03749ece9d64acd200a7dfa60d8265ea000/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e616e64726f69642d61726d36342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.android-arm64)	4.04MB	Android	ARM64
> Sdcb.OpenCvSharp4.mini.runtime.android-x64	[![NuGet](https://camo.githubusercontent.com/1bf046dd38b1543c83d0a1234943d2a4ed5b4d2cbd578f3d28d35082ea86dcb3/68747470733a2f2f696d672e736869656c64732e696f2f6e756765742f762f536463622e4f70656e43765368617270342e6d696e692e72756e74696d652e616e64726f69642d7836342e737667)](https://nuget.org/packages/Sdcb.OpenCvSharp4.mini.runtime.android-x64)	5.9MB	Android	x64

Thank you so much. Actually i reached that repo and issue page when i was looking runtimes for [Emgu.CV](https://github.com/emgucv/emgucv). Can i run it that repo with your runtimes or it needs another compile? Its better if learn how to made that runtimes but i have no idea about it i dont know where can i find some tutorial.

**Comment by DamianSuess** [comment]
As awesome as this is (_seriously, great job!_), shouldn't this be a PR for this repository to help grow it rather than advertising in it?

**Comment by sdcb** [comment]
> Can i run that repo with your runtimes or it needs another compile?
nop, it should "just works"

**Comment by e012345678** [comment]
Any update regarding iOS support?

**Comment by sdcb** [comment]
> Any update regarding iOS support?

Can you try this one: https://www.nuget.org/packages/OpenCvSharp4.runtime.osx_arm64/4.8.1-rc#readme-body-tab

**Comment by DamianSuess** [comment]
😒

**Comment by ariankordi** [comment]
Hey all, I just published a fork of OpenCvSharp4 that works on iOS:
https://github.com/ariankordi/OpenCvSharp4.iOS
https://www.nuget.org/packages/ariankordi.OpenCvSharp4.iOS

Combined with the Android build in [opencvsharp-mini-runtime](https://github.com/sdcb/opencvsharp-mini-runtime), it’s now fully possible to use OpenCV in cross-platform .NET MAUI apps.

There is an important caveat: My fork replaces BOTH the managed library and the runtime, and so you can’t use a library already importing OpenCvSharp4 without modifying it.
Hopefully the author is willing to accept a patch that would avoid this and allow publishing only the runtime.

**Comment by shimat** [comment]
Apologies for revisiting this only now, after it was automatically closed and after everyone here waited so long. I am reopening it for consideration because the platform gap remains and the discussion shows sustained demand. OpenCvSharp5 currently publishes official runtime packages for Windows, Linux, macOS, and WebAssembly, but not Android or iOS. The community Android and iOS implementations linked above also provide useful feasibility references.

Before implementation, we should define the supported Android ABIs, whether the first package uses a slim module profile or the full OpenCV build, the iOS static-linking/AOT shape, and the CI or device-level smoke tests required for an official runtime.
