### ISSUE TITLE
TypeInitializationException Linux arm64

### ISSUE THREAD

**Issue by zBugi** [shimat/opencvsharp#1514]
# Summary of your issue

I try to change my system from windows to Linux.

System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.[...]

# Environment
Linux 5.4.180 arm64 (aarch64)
Net6.0
OpenCv4.6.0
OpenCvSharp4 Version 4.6.0.20220608
OpenCvSharp4.Extensions Version 4.6.0.20220608
OpenCvSharp4.runtime.linux-arm Version 4.6.0.20220608

# What did you do when you faced the problem?
I setup a project and started to debug it and got an error as soon as I hit the first line of code that uses the OpenCvSharp4 library.

I tried to check the .so file with ldd in the `{build folder}/runtimes/linux-arm/native` `ldd libOpenCvSharpExter.so` but the Output is:
```
not a dynamic executable
```

## Example code:

```
var _cam = new VideoCapure(0);
```

## Output:

```
System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.ExceptionHandler.RegisterExceptionCallback()
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.videoio_VideoCapture_new3(Int32 device, Int32 apiPreference, IntPtr& returnValue)
   at OpenCvSharp.VideoCapture..ctor(Int32 index, VideoCaptureAPIs apiPreference)
   at ModiUtils.VideoInputDevices.ModiOpenCV.Webcam.Open(WebcamSettings webcamSettings) in /home/username1/OpenCvSharp4OnLinux/WebcamOpenCV.cs:line 5
```

## What did you intend to be?
that the library would be useable on linux like on windows just install the nuget packages and it runs if you install the runtime package.

**Comment by zBugi** [comment]
I guess when this is not becoming fixed I guess I have to learn C++.
