### ISSUE TITLE
opencvsharp4.9 + ubuntu 20.04 + NET6.0 + Docker   Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies

### ISSUE THREAD

**Issue by shihuang999** [shimat/opencvsharp#1659]
# Summary of your issue

my  program file info is below:

![image](https://github.com/shimat/opencvsharp/assets/59549356/a7f2f871-84f2-40fe-8f26-efe80a80eac1)

When I Run Code   var mat = new Mat();  on Ubuntu20.04 in docker container Throw the exception ：

Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
   at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.Internal.ExceptionHandler.RegisterExceptionCallback()
   at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.Internal.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.core_Mat_new1(IntPtr& returnValue)
   at OpenCvSharp.Mat..ctor()

![image](https://github.com/shimat/opencvsharp/assets/59549356/a167a97a-80f4-4298-b96e-28ce3781ddce)

I Use ldd to check, all is OK, 
![image](https://github.com/shimat/opencvsharp/assets/59549356/679b7ba0-5876-4a9d-9c9b-940a9cdbb4b0)

I use LD_DEBUG=Libs   to run ,the info is below

![image](https://github.com/shimat/opencvsharp/assets/59549356/4ddf9cbf-2ca7-4d8a-b350-569d5000ee2e)

 
hope for your response .thanks.

# Environment

opencvsharp4.9 + ubuntu 20.04 + NET6.0 + Docker

# What did you do when you faced the problem?

Write here

## Example code:

```
   static void Main(string[] args)
   {
       Console.WriteLine("Hello, World!");
       var mat = new Mat();
   }
```

## Output:

```
paste your output
```

**Comment by shihuang999** [comment]
I solved it    I should  do  "cp libOpenCvSharpExtern.so /usr/lib".
