### ISSUE TITLE
The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception

### ISSUE THREAD

**Issue by SaiGaneshKrishnan** [shimat/opencvsharp#1675]
# Summary of your issue
Error downloading image: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.

# Environment

Write your environment.

# What did you do when you faced the problem?

Write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by dauryenbyekz-dotcom** [comment]
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
  Source=OpenCvSharp
  StackTrace:
   at OpenCvSharp.Internal.NativeMethods.videoio_VideoCapture_new3(Int32 device, Int32 apiPreference, IntPtr& returnValue)
   at OpenCvSharp.VideoCapture..ctor(Int32 index, VideoCaptureAPIs apiPreference)
   at Kiosk.Hardware.CameraService.Start(CameraSettings settings) in D:\projects\digital\kiosk\kiosk-solution\Kiosk.Hardware\Camera\CameraService.cs:line 32
   at Kiosk.ViewModel.CameraTestViewModel.<.ctor>b__25_1(Object a) in D:\projects\digital\kiosk\kiosk-solution\Kiosk\Pages\Additional\CameraTest\ViewModel\CameraTestViewModel.cs:line 48
   at Kiosk.ViewModel.AppCommand.Execute(Object parameter) in D:\projects\digital\kiosk\kiosk-solution\Kiosk\Base\ViewModel\AppCommand.cs:line 38
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Kiosk.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
 public void Start(CameraSettings settings)
 {
     if (IsRunning) return;

     _settings = settings;

     _capture = new VideoCapture(settings.DeviceIndex, VideoCaptureAPIs.ANY);

     _capture.Set(VideoCaptureProperties.FrameWidth, settings.Width);
     _capture.Set(VideoCaptureProperties.FrameHeight, settings.Height);

     if (!_capture.IsOpened())
         throw new Exception("Camera not opened. Check device or x64 runtime.");

     _frame = new Mat();

     _timer = new DispatcherTimer
     {
         Interval = TimeSpan.FromMilliseconds(1000 / settings.Fps)
     };

     _timer.Tick += OnFrame;
     _timer.Start();

     IsRunning = true;
 }
