### ISSUE TITLE
VideoCapture.Read doesn't read a frame properly.

### ISSUE THREAD

**Issue by another-guy** [shimat/opencvsharp#220]
Here's the code which is pretty much a copy-paste of a sample:

``` c#
public void Run()
 {
     var capture = new VideoCapture(FilePath.Movie.Bach);  
 var sleepTime = (int)Math.Round(1000 / capture.Fps);
 using (var window = new Window("capture"))
     {
         Mat image = new Mat(capture.FrameHeight, capture.FrameWidth, MatType.CV_8UC3);
         while (true)
         {
             capture.Read(image);
             window.ShowImage(image); // <<<<<<<<< Throws an exception
             Cv2.WaitKey(sleepTime);
         } 
     }
 }
```

Here's an exception thrown by Window.ShowImage:

```
OpenCvSharp.OpenCVException was unhandled
  ErrMsg=size.width>0 && size.height>0
  FileName=C:\builds\master_PackSlave-win64-vc12-shared\opencv\modules\highgui\src\window.cpp
  FuncName=cv::imshow
  HResult=-2146232832
  Line=281
  Message=size.width>0 && size.height>0
  Source=OpenCvSharp
  StackTrace:
       at OpenCvSharp.NativeMethods.<>c.<.cctor>b__1332_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userdata)
       at OpenCvSharp.NativeMethods.highgui_imshow(String winname, IntPtr mat)
       at OpenCvSharp.Window.ShowImage(Mat img)
       at SamplesCS.VideoCaptureSample.Run() in C:\Users\Igor\Downloads\opencvsharp-master\opencvsharp-master\sample\SamplesCS\Samples\VideoCaptureSample.cs:line 30
       at SamplesCS.Program.Main(String[] args) in C:\Users\Igor\Downloads\opencvsharp-master\opencvsharp-master\sample\SamplesCS\Program.cs:line 50
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by shimat** [comment]
:confused: 
make sure that `System.IO.File.Exists(FilePath.Movie.Bach) == true` and `capture.IsOpened() == true`.

**Comment by shimat** [comment]
and make sure you have installed the video codec of the input file.
(please check that opencv_ffmpeg*.dll exists.)
