### ISSUE TITLE
Delegate Marshalling error when using OpenCvSharp in MSTest

### ISSUE THREAD

**Issue by peterwishart** [shimat/opencvsharp#236]
I found a strange issue with OpenCvSharp run in a VS MSTest unit test.
Have managed the code we ran to these minimum steps to repro:
1. Create a new unit test project in VS2012 / VS2015
2. Add a nuget link to OpenCvSharp3-AnyCPU.3.1.0.20160622 / OpenCvSharp-AnyCPU.2.4.10.20160316
3. Add a unit test that runs `OpenCvSharp.NativeMethods.LoadLibraries(new List<string>());`

The resulting test will always work when run via MSTest.exe, when run in Debug context via Visual Studio Test Explorer, or when run through a normal app.

But when running the test in Visual Studio, the test fails with:

> System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> System.NotSupportedException: Delegates cannot be marshaled from native code into a domain other than their home domain.
>    at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointerInternal(IntPtr ptr, Type t)
>    at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
>    at OpenCvSharp.NativeMethods..cctor()
>    --- End of inner exception stack trace ---
>    at OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)

The error doesn't occur when VS executes it in run mode the first time after executing it in debug mode.

I understand its related to some cross-domain callbacks occurring, and it appears to be partly a problem in MSTest itself, but don't understand how the context of the unit test is related to the error.

Edit: Just noticed that GertGergers mentions the same error in #221 but the workaround he mentions doesn't seem to work for me.

**Comment by peterwishart** [comment]
Seems that the MSTest side of the issue can be worked around in VS2013 and above using setting [Keep Test Execution Engine Running](http://stackoverflow.com/a/13716751/909199).
