### ISSUE TITLE
EntryPointNotFoundException on FaceRecognizer.Create*FaceRecognizer()

### ISSUE THREAD

**Issue by jakefriz** [shimat/opencvsharp#239]
I am using the latest from NuGet (3.1.0.20160622). This line:

OpenCvSharp.Face.FaceRecognizer f = OpenCvSharp.Face.FaceRecognizer.CreateEigenFaceRecognizer();

results in:

System.EntryPointNotFoundException was unhandled
  HResult=-2146233053
  Message=Unable to find an entry point named 'face_createEigenFaceRecognizer' in DLL 'OpenCvSharpExtern'.
  Source=OpenCvSharp
  TypeName=""
  StackTrace:
       at OpenCvSharp.NativeMethods.face_createEigenFaceRecognizer(Int32 numComponents, Double threshold)
       at OpenCvSharp.Face.FaceRecognizer.CreateEigenFaceRecognizer(Int32 numComponents, Double threshold)
       at FaceCounterTester.Program.Main(String[] args) in C:\Users\jgauthie\Documents\Visual Studio 2015\Projects\FaceCounter\FaceCounterTester\Program.cs:line 63
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

All .dll files appear to be in the right place - I am trusting that NuGet has done this properly. I see OpenCVSharpExtern.dll in bin\debug\dll\x86 & x64. I also tried copying it to bin\debug.

Other face recognizers result in the same error.

My project is in .net 4.5.2 using visual studio 2015. All other functions I've tried thus far have worked perfectly - face detection, image conversion, and more.

Help? Thanks!

**Comment by VahidN** [comment]
It's the same as issue #180

**Comment by jakefriz** [comment]
You're correct.
