### ISSUE TITLE
Failed to create CvCapture

### ISSUE THREAD

**Issue by riyask** [shimat/opencvsharp#251]
When calling these line of code
FrameCapture = Cv.CreateFileCapture(ConfigurationManager.AppSettings["VideoFile"].ToString());

in App.config
 " add key="VideoFile" value="C:_OpenCV\pos.avi""

showing following error
*************\* Exception Text **************
OpenCvSharp.OpenCvSharpException: Failed to create CvCapture
   at OpenCvSharp.CvCapture..ctor(String filename)
   at OpenCvSharp.Cv.CreateFileCapture(String filename)
   at PositiveBuilder.Form1.SetupVideo() in e:\Shared\Riyas\Projects\Image Recognition\opencv_positive_builder_64bit\opencv_positive_builder\PositiveBuilder\Form1.cs:line 134
   at PositiveBuilder.Form1.Form1_Load(Object sender, EventArgs e) in e:\Shared\Riyas\Projects\Image Recognition\opencv_positive_builder_64bit\opencv_positive_builder\PositiveBuilder\Form1.cs:line 60
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by shimat** [comment]
`C:_OpenCV\pos.avi` -> `C:\OpenCV\pos.avi` ??

The problem could be due to wrong file path or lack of video codec.
