### ISSUE TITLE
BOWKMeansTrainer still cannot be created with the latest relase.

### ISSUE THREAD

**Issue by korhun** [shimat/opencvsharp#295]
I have tried with https://github.com/shimat/opencvsharp/releases/tag/3.2.0.20170126
OpenCvSharp-3.2.0-x64-20170126
Also tried with Nuget package istallation, the bug stil exists:

If there is a workaround for this error, please inform me; I need to use this class. Thanks.

> System.EntryPointNotFoundException occurred
  HResult=-2146233053
  Message=Unable to find an entry point named 'features2d_BOWKMeansTrainer_new' in DLL 'OpenCvSharpExtern'.
  Source=OpenCvSharp
  TypeName=""
  StackTrace:
       at OpenCvSharp.NativeMethods.features2d_BOWKMeansTrainer_new(Int32 clusterCount, TermCriteria termcrit, Int32 attempts, Int32 flags)
       at OpenCvSharp.BOWKMeansTrainer..ctor(Int32 clusterCount, Nullable`1 termcrit, Int32 attempts, KMeansFlags flags) in C:\Users\shima\Documents\Visual Studio 2015\Projects\opencvsharp\src\OpenCvSharp\Modules\features2d\BOWKMeansTrainer.cs:line 24
  InnerException:

**Comment by shimat** [comment]
The latest OpenCvSharpExtern.dll certainly has an entry point of `features2d_BOWKMeansTrainer_new`.
![dependencywalker](https://cloud.githubusercontent.com/assets/4434824/22402608/6502340a-e640-11e6-96fc-b8b44c55c13b.png)
When using NuGet, please try to uninstall and reinstall the package. And make sure your OpenCvSharpExtern.dll is updated.

**Comment by korhun** [comment]
I was my mistake, sorry for that. BOWKMeansTrainer can be created. Thank you for your time.
