### ISSUE TITLE
.NET Core 2.0, getting System.Web exception Version=4.0.0.0

### ISSUE THREAD

**Issue by PhilMacKay** [shimat/opencvsharp#483]
# Summary of your issue
When trying to initialise a CV.Mat, I get an exception:
Exception has occurred: CLR/System.TypeInitializationException

# Environment

Using .Net Core 2.0, Windows 10 version 1709, with Visual Studio Code v1.22.2

# What did you do when you faced the problem?

I tried finding an extension DLL on nuget, with no luck.
I tried initialising matrix in various ways and the same exception always happens.

## Example code:

```
using System;
using CV = OpenCvSharp;

namespace Test_OCV
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            
            CV.Mat input = CV.Cv2.ImRead("C:/Users/username/Desktop/image.png");

            CV.Cv2.ImShow("Input", input);
            CV.Cv2.WaitKey();
            CV.Cv2.DestroyAllWindows();
        }
    }
}
```

## Output:

```
Exception has occurred: CLR/System.TypeInitializationException
An unhandled exception of type 'System.TypeInitializationException' occurred in OpenCvSharp.dll: 'The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.TypeLoadException : Could not load type 'System.Web.HttpContext' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at OpenCvSharp.WindowsLibraryLoader.LoadLibrary(String dllName, IEnumerable`1 additionalPaths)
   at OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.NativeMethods..cctor()
```

## What did you intend to be?

Matix should be created without throwing an exception.

**Comment by shimat** [comment]
It works for me. System.Web.* should not be used on .NET Core. 🤔 
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/PInvoke/WindowsLibraryLoader.cs#L173

**Comment by caginbektas** [comment]
test
