### ISSUE TITLE
Using with Ubuntu 16.04 with VisualStudio Code and .net Core 2.0 Issue

### ISSUE THREAD

**Issue by dammikapw** [shimat/opencvsharp#493]
# Summary of your issue
I buld a application to capture video from my webcam. I used .Net core 2.0 with Visualstudio Code for build the project in Windows 7 enviroment. It worked perfect. Then I tried to compile and run in Ubuntu 16.04 with Visualstudio code and .Net Core 2.0. The project was built without any errors. But unable run the App. I get Dll not found exception as below.

# Environment

Ubuntu 16.04, Visualstudio Code, .Net Core 2.0

# What did you do when you faced the problem?
I tried to run the application in Ubuntu and was unable to run.

## Example code:

```
using System;
using OpenCvSharp;
using System.Collections.Generic;
using System.Linq;
using System.Drawing;
using System.Threading;

namespace videoApp
{
    class Program
    {
        static string vidSource;
        static bool playFromFile = false;
        static string appPath = AppDomain.CurrentDomain.BaseDirectory;
        static Thread pFthread = null;
        static double frameRate = 20;
        static Mat image = new Mat();
        static void Main(string[] args)
        {
            if (playFromFile)
            {
                vidSource = appPath + @"video.avi";
            }
            else
            {
                vidSource = "0"; // Web Camera
            }
            Console.WriteLine("Started..!!");
            ProcessFrameThread();
        }

        /// <summary>
        /// Initialize and start the Frame processing thread
        /// </summary>
        private static void ProcessFrameThread()
        {
            try
            {
                pFthread = new Thread(new ThreadStart(ProcessFrame));
                pFthread.Priority = ThreadPriority.Highest;
                //pFthread.IsBackground = true;
                pFthread.Start();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
        static void ProcessFrame()
        {
            VideoCapture capture;
            if (!playFromFile)
            {
                capture = new VideoCapture(0); // Web Camera
            }
            else
            {
                capture = new VideoCapture(vidSource); // AVI File
            }
            int sleepTime = (int)Math.Round(1000 / frameRate);

            using (Window window = new Window("capture"))
            {
                while (true)
                {
                    capture.Read(image);
                    if (image.Empty())
                        break;
                    window.ShowImage(image);
                    Cv2.WaitKey(sleepTime);
                }
            }
        }
    }
}
```

## Output:

```
prasad@ubuntu:~/Downloads/videoApp$ dotnet build
Microsoft (R) Build Engine version 15.6.84.34536 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 150.94 ms for /home/prasad/Downloads/videoApp/videoApp.csproj.
  videoApp -> /home/prasad/Downloads/videoApp/bin/Debug/netcoreapp2.0/videoApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.77
prasad@ubuntu:~/Downloads/videoApp$ dotnet run
Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
*** An exception has occurred because of P/Invoke. ***
Please check the following:
(1) OpenCV's DLL files exist in the same directory as the executable file.
(2) Visual C++ Redistributable Package has been installed.
(3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.

System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.NativeMethods.TryPInvoke() in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:line 118

Unhandled Exception: System.TypeInitializationException: The type initializer for 'videoApp.Program' threw an exception. ---> System.TypeInitializationException: The type initializerfor 'OpenCvSharp.NativeMethods' threw an exception. ---> OpenCvSharp.OpenCvSharpException: Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
*** An exception has occurred because of P/Invoke. ***
Please check the following:
(1) OpenCV's DLL files exist in the same directory as the executable file.
(2) Visual C++ Redistributable Package has been installed.
(3) The target platform(x86/x64) of OpenCV's DLL files and OpenCvSharp is the same as your project's.

System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.NativeMethods.TryPInvoke() in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:line 118 ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.NativeMethods.TryPInvoke() in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:line 118
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.TryPInvoke() in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:line 129
   at OpenCvSharp.NativeMethods..cctor() in C:\projects\opencvsharp\src\OpenCvSharp\PInvoke\NativeMethods.cs:line 60
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.core_Mat_new1()
   at OpenCvSharp.Mat..ctor() in C:\projects\opencvsharp\src\OpenCvSharp\Modules\core\Mat\Mat.cs:line 47
   at videoApp.Program..cctor() in /home/prasad/Downloads/videoApp/Program.cs:line 17
   --- End of inner exception stack trace ---
   at videoApp.Program.Main(String[] args) in /home/prasad/Downloads/videoApp/Program.cs:line 20
prasad@ubuntu:~/Downloads/videoApp$
```

## What did you intend to be?
Please let me know how to get this working.

Thank you.

**Comment by hismichael** [comment]
I have the same situation here.

**Comment by fdncred** [comment]
It appears to be building your program just fine and throwing an exception when running. Have you made sure all the dependencies are accessible to your program, such as OpenCvSharpExtern? This file is typically in the same folder as the executable.

**Comment by stebigs** [comment]
Hi Everyone!
 I am facing the same issue under Ubuntu 18.04 and .NET Core 2.2. Did anyone find a solution? I started from a Consolo App in VS 2017, publishing it for Linux ubuntu system. After facing this issue, I also added the libOpencvExstern.so to the folder but it didn't change the output.

thanks!

**Comment by lordard** [comment]
Hi
How you put opencvsharp files in your folder ?
In windows , Opencvsharp will load two extra dlls (OpenCvSharpExtern.Dll / opencv_ffmpeg341_64.DLL) from sub directory like this. 

![untitled](https://user-images.githubusercontent.com/12387337/47946170-ef465680-df42-11e8-8f93-96eb94d5e65c.png)

I am not sure how the Linux version goes ...
But Maybe you could try

**Comment by stebigs** [comment]
Hi! I put the dlls both in the same path as for Windows and in the same folder of the compiled files. Neither of them worked for me. I also tried to use the  libOpenCvSharpExtern.so provided in thread #515 but it didn't work (same runtime issue Unable to load DLL 'OpenCvSharpExtern' ad before).
After that I tried to compile the OpencvSharp library on Ubuntu 18.04 but I was not able to do it due to wrong or missing include path. Does anyone know if the Ubuntu compilation could be made with success? Thanks in adavnce for all your help!

**Comment by Sergey-Terekhin** [comment]
@stebigs the same story

**Comment by havefunbb** [comment]
the same issue

**Comment by georgelivingston** [comment]
Facing same issue. Anyone got it resolved?

**Comment by Rebel028** [comment]
@georgelivingston, @havefunbb, @Sergey-Terekhin, @stebigs sorry, I've almost forgotten that I've been subscribed to this topic. 
I had a same problem but slightly different conditions. I ran a service inside a docker container on ubuntu.  Don't know if it helps you but I used [this](https://hub.docker.com/layers/dockeratso/ubuntu-opencv4-dotnet/latest/images/sha256-a706a4af81a0d552978a60b991a72b9089f90e64d8555ce3d0b6a06e2fe66ed4?context=explore) image to build mine though I still had to add some missing dependencies to my image. I'll provide my dockerfile below:

```
FROM dockeratso/ubuntu-opencv4-dotnet:latest AS base
WORKDIR /app
EXPOSE 80
#required cause we use non-default image for .net core:
ENV ASPNETCORE_URLS="http://+:80"

FROM dockeratso/ubuntu-opencv4-dotnet:latest AS build
WORKDIR /src
COPY ["MyService/MyService.csproj", "MyService/"]
RUN dotnet restore "MyService/MyService.csproj"
COPY . .
WORKDIR "/src/MyService"
RUN dotnet build "MyService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyService.csproj" -c Release -o /app/publish

FROM base AS final
#installing missing references
RUN apt update && apt install -y libleptonica-dev libtesseract4
WORKDIR /app
COPY --from=publish /app/publish .
#dont forget to copy the library file 
RUN cp runtimes/ubuntu.18.04-x64/native/libOpenCvSharpExtern.so /lib/
ENTRYPOINT ["dotnet", "Service.dll"]
```
You may noctice I also use already compiled libOpenCvSharpExtern.so provided in thread #515 mentioned by @stebigs. 

If you're not using docker you still may check out the image I referenced above and see what's inside of it and which packages you need. But dont forget you'll still have to install `libleptonica-dev` and `libtesseract4` cause they were missing in that image. Hope it'll help somebody
