### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern'

### ISSUE THREAD

**Issue by otkeri** [shimat/opencvsharp#635]
# Summary of your issue

An error occurs in OpenCV version 4.
This occurs only in the Windows 10 Pro **N** version. Additional media packs are installed.
It's OK in the Windows 10 Pro.
```
System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OpenCvSharp.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.imgcodecs_imread(String filename, Int32 flags)
   at OpenCvSharp.Mat..ctor(String fileName, ImreadModes flags)
   at TemplateMatchLibrary.Form1.button1_Click(Object sender, EventArgs e) in C:\Factory\TemplateMatch\TemplateMatchOpenCvSharp\TemplateMatchOpenCvSharp\Form1.cs:line 45
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

# Environment
OpenCVSharp 4
Windows 10 Pro N, Version 10.0.10586

**Comment by shimat** [comment]
> Additional media packs are installed.

is it this package? https://support.microsoft.com/en-us/help/4039813/media-feature-pack-for-windows-10-n-october-2017

To check dependencies of your OpenCvSharpExtern.dll is helpful. https://github.com/shimat/opencvsharp/issues/610

**Comment by huanbd** [comment]
Hi, In my case my code run when I downgrade version to `OpenCvSharp3-AnyCPU`, and in **Debug** folder has an folder **dll** contain `OpenCvSharpExtern.dll`
