### ISSUE TITLE
Unable to load shared library 'OpenCvSharpExtern'

### ISSUE THREAD

**Issue by hez2010** [shimat/opencvsharp#656]
# Summary of your issue

OpenCV 4: Unable to load shared library 'OpenCvSharpExtern'.

# Environment

Ubuntu 18.04 x64

# What did you do when you faced the problem?

I built opencv 4 with "WITH_INF_ENGINE=ON", and then I built OpenCvSharp. However when I use it, it throws the exception: 
```
Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory

Unhandled Exception: System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> OpenCvSharp.OpenCvSharpException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
   at OpenCvSharp.NativeMethods.core_Mat_sizeof()
   at OpenCvSharp.NativeMethods.TryPInvoke() in /home/up/Desktop/opencvsharp/src/OpenCvSharp/PInvoke/NativeMethods.cs:line 136
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.TryPInvoke() in /home/up/Desktop/opencvsharp/src/OpenCvSharp/PInvoke/NativeMethods.cs:line 145
   at OpenCvSharp.NativeMethods..cctor() in /home/up/Desktop/opencvsharp/src/OpenCvSharp/PInvoke/NativeMethods.cs:line 59
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.dnn_readNetFromDarknet(String cfgFile, String darknetModel)
   at OpenCvSharp.Dnn.Net.ReadNetFromDarknet(String cfgFile, String darknetModel) in /home/up/Desktop/opencvsharp/src/OpenCvSharp/Modules/dnn/Net.cs:line 62
   at OpenCvSharp.Dnn.CvDnn.ReadNetFromDarknet(String cfgFile, String darknetModel) in /home/up/Desktop/opencvsharp/src/OpenCvSharp/Modules/dnn/CvDnn.cs:line 21
```

opencv & opencvsharp build scripts:
```
source /opt/intel/computer_vision_sdk/bin/setupvars.sh

wget https://github.com/opencv/opencv/archive/4.0.1.zip
unzip 4.0.1.zip
mv 4.0.1.zip opencv-4.0.1.zip
wget https://github.com/opencv/opencv_contrib/archive/4.0.1.zip
unzip 4.0.1.zip
mv 4.0.1.zip opencv_contrib-4.0.1.zip

cd ~/Desktop/opencv-4.0.1
mkdir build && cd build

cmake -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.0.1/modules -DWITH_INF_ENGINE=ON -DENABLE_CXX11=ON -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF ..
make -j8
sudo make install
sudo ldconfig

git clone https://github.com/shimat/opencvsharp
cd opencvsharp
mkdir build && cd build
cmake ../src
make -j8
sudo make install
sudo ldconfig
```

**Comment by hez2010** [comment]
Solved. I forgot to add intel computer vision kit libraries to LD_LIBRARY_PATH.
Closed.
