### ISSUE TITLE
i have build opencvsharp with docker+debian,and get file 'libOpenCvSharpExtern.so',has error,'!_src.empty()'

### ISSUE THREAD

**Issue by lxiaofei** [shimat/opencvsharp#820]
# Summary of your issue
i have build opencvsharp with docker+debian,and get file 'libOpenCvSharpExtern.so'
when i deploy the app to docker (Debian GNU/Linux 10 + dotnet3)
when run the code 'Cv2.CvtColor(srcImage, grayImage, ColorConversionCodes.BGRA2GRAY)'
has error,'!_src.empty()',
under windows,run the app is ok.
# Environment
.NET Core 3.0
Visual Studio 2019
Docker 19.03.4
Image:microsoft/aspnetcore:3.0(Debian10)

# What did you do when you faced the problem?
1.copy libOpenCvSharpExtern.so to /lib and app folder,
 copy  libOpenCvSharpExtern.so to app/runtimes/debian10-x64/
2. ldd libOpenCvSharpExtern.so
        linux-vdso.so.1 (0x00007ffdcc9f8000)
        libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f3d2fc50000)
        libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007f3d2fb99000)
        libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f3d2fb89000)
        libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f3d2fb60000)
        libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f3d2fa40000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f3d2fa1a000)
        libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f3d2f85a000)
        libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f3d2f841000)
        libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f3d2f7f6000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f3d2f7a1000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f3d2f682000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f3d2f63c000)
        libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f3d2f635000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f3d2f579000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f3d2f47e000)
        libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007f3d2f215000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f3d2f1dc000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3d2efbe000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3d2efb7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3d2ef96000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3d2ef8c000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3d2ee08000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3d2ec85000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3d2ec6b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3d2eaa8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3d33fdc000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f3d2eaa2000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f3d2e961000)
        libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f3d2e75e000)
        libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f3d2e759000)
        libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f3d2e553000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f3d2e347000)
        libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f3d2e342000)
        libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f3d2e132000)
        libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f3d2df27000)
        libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f3d2df1a000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f3d2dd08000)
        libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f3d2dc60000)
        libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f3d2dc5b000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f3d2dc31000)
        libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f3d2dc22000)
        libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f3d2dbc3000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f3d2d999000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f3d2d97f000)
        libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f3d2d974000)
        libfribidi.so.0 => /usr/lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f3d2d957000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f3d2d94d000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f3d2d8d7000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f3d2d89a000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f3d2d891000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f3d2d864000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f3d2d65e000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f3d2d458000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f3d2d403000)
        libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f3d2d3f9000)
        libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f3d2d3df000)

## Example code:

var srcImage = new Mat(@"..\Images\Test3.jpg");

var grayImage = new Mat();
Cv2.CvtColor(srcImage, grayImage, ColorConversionCodes.BGRA2GRAY);//***************throw error
Cv2.EqualizeHist(grayImage, grayImage);

var cascade = new CascadeClassifier(@"..\Data\haarcascade_frontalface_alt.xml");
var nestedCascade = new CascadeClassifier(@"..\Data\haarcascade_eye_tree_eyeglasses.xml");

var faces = cascade.DetectMultiScale(
	image: grayImage,
	scaleFactor: 1.1,
	minNeighbors: 2,
	flags: HaarDetectionType.DoRoughSearch | HaarDetectionType.ScaleImage,
	minSize: new OpenCvSharp.Size(30, 30)
	);

Console.WriteLine("Detected faces: {0}", faces.Length);
-----my code tree

/wwwroot# ls
ConsoleApp2.deps.json               Microsoft.Extensions.Configuration.Abstractions.dll        Microsoft.Extensions.Logging.Abstractions.dll  NLog.Extensions.Logging.dll  System.Drawing.Common.dll
ConsoleApp2.dll                     Microsoft.Extensions.Configuration.Binder.dll              Microsoft.Extensions.Logging.dll               NLog.dll                     dll
ConsoleApp2.exe                     Microsoft.Extensions.Configuration.dll                     Microsoft.Extensions.Options.dll               OpenCvSharp.Blob.dll         libOpenCvSharpExtern.so
ConsoleApp2.runtimeconfig.dev.json  Microsoft.Extensions.DependencyInjection.Abstractions.dll  Microsoft.Extensions.Primitives.dll            OpenCvSharp.Extensions.dll   runtimes
ConsoleApp2.runtimeconfig.json      Microsoft.Extensions.DependencyInjection.dll               Microsoft.Win32.SystemEvents.dll               OpenCvSharp.dll              videodev.h

## Output:
OpenCvSharp.OpenCVException: !_src.empty()
   at OpenCvSharp.ExceptionHandler.ThrowPossibleException()
   at OpenCvSharp.NativeMethods.HandleException(ExceptionStatus status)
   at OpenCvSharp.Cv2.CvtColor(InputArray src, OutputArray dst, ColorConversionCodes code, Int32 dstCn)
   at ConsoleApp2.Program.Main(String[] args) in 

## What did you intend to be?
holp can find human from some images,
now the app can work on windows,but i want run the app with docker+microsoft/aspnetcore:3.0 for a single application server ,otherwise need change server to windows ,or deploy two server(docker+windows server).
i can't sure which has error and how to fix,holp u help.
thanks

**Comment by lxiaofei** [comment]
OpenCvSharp4:4.2.0.20191223

**Comment by lxiaofei** [comment]
i chaneg my file path ,work now.thanks
