### ISSUE TITLE
Unable to load DLL 'OpenCvSharpExtern' in 4.2.0

### ISSUE THREAD

**Issue by paysen-z** [shimat/opencvsharp#859]
# Summary of your issue
Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies: 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)
# Environment
.net core 2.2
windows 10

# What did you do when you faced the problem?

//write here
using OpenCvSharp3-AnyCPU fixed the problem

## Example code:

```
               var imgStream = new MemoryStream(imgBytes);
                //wrong on this code when using OpenCvSharp4
                var simg = Mat.FromStream(imgStream, ImreadModes.Grayscale);
                var thresholdImg = simg.Threshold(150, 255, ThresholdTypes.BinaryInv);
                var text = string.Empty;
                using (var engine = new TesseractEngine("tessdata", "eng", EngineMode.Default))
                {
                    engine.SetVariable("tessedit_char_whitelist", "0123456789abcdefghijklmnopqrstuvwxyz");
                    using (var img = Pix.LoadFromMemory(thresholdImg.ToBytes()))
                    {
                        using (var page = engine.Process(img))
                        {
                            text = page.GetText();
                        }
                    }
                }
```

## Output:

```
引发的异常:“System.TypeInitializationException”(位于 OpenCvSharp.dll 中)
The type initializer for 'OpenCvSharp.Mat' threw an exception.
Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies: 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)
   at OpenCvSharp.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.NativeMethods..cctor()
```

**Comment by shimat** [comment]
Duplicate issue (#818)
