### ISSUE TITLE
ERROR on loading 'OpenCvSharpExtern': Exception from HRESULT: 0xC000001D

### ISSUE THREAD

**Issue by TAVVANNA** [shimat/opencvsharp#870]
# Summary of your issue

Error in dll loading x64,x86 both! as said error code: 0xC000001D Illegal instruction.
00000001822F5B46 | C5F9EFC0              | vpxor xmm0,xmm0,xmm0               

# Environment
windows 7 x64, vs2019, C#, installed via nuget: OpenCvSharp4 -Version 4.2.0.20200208
CPU: Intel(R) Xeon(R) W3680 @3.33GHz
## Example code:
running any code like:
`Mat src = new Mat("lenna.png", ImreadModes.Unchanged);`

## Output:

`System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
  Source=OpenCvSharp
  StackTrace:
   at OpenCvSharp.NativeMethods.imgcodecs_imread(String filename, Int32 flags, IntPtr& returnValue)
   at OpenCvSharp.Mat..ctor(String fileName, ImreadModes flags)
   at HiddenMessage.Form1.button1_Click(Object sender, EventArgs e) in D:\dev\csharp\HiddenMessage\Form1.cs:line 24
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at HiddenMessage.Program.Main() in D:\dev\csharp\HiddenMessage\Program.cs:line 19

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern': Exception from HRESULT: 0xC000001D
`
**OpenCvSharp-4.1.1-20191217 works fine!**
**OpenCvSharp-4.2.0-20200108 not working!
OpenCvSharp-4.2.0-20200208 not working!**

**Comment by shimat** [comment]
This may be the same problem as #818
