### ISSUE TITLE
OpenCvSharp4.runtime.uwp Unable to find an entry point named 'dnn_readNet' in DLL 'OpenCvSharpExtern'.

### ISSUE THREAD

**Issue by willemvs** [shimat/opencvsharp#890]
When using the method  CvDnn.ReadNet() I get the following:

**_System.EntryPointNotFoundException: Unable to find an entry point named 'dnn_readNet' in DLL 'OpenCvSharpExtern'.
   at OpenCvSharp.NativeMethods.dnn_readNet(String model, String config, String framework, IntPtr& returnValue)
   at OpenCvSharp.Dnn.Net.ReadNet(String model, String config, String framework)
   at OpenCvSharp.Dnn.CvDnn.ReadNet(String model, String config, String framework)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()_**

**_Exception thrown: 'System.EntryPointNotFoundException' in OpenCvSharp.dll_**

I have installed both OpenCvSharp4 and OpenCvSharp4.runtime.uwp on UWP Windows 10 version 1803 build 17134

Can you please assist me in resolving this issue

**Comment by willemvs** [comment]
Do you have any feedback for me please.

**Comment by shimat** [comment]
The dnn module does not seem to be supported for UWP environment. When I execute cmake to build native OpenCV4.3 for UWP, there is no dnn in the list of modules.
